name: telegram_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0
 

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.1
  general_lib: ^0.0.1
  image: ^4.1.3
  isar: ^3.1.0+1
  mason_logger: ^0.2.9
  path: ^1.8.3
  stack_trace: ^1.11.1
  supabase: ^1.11.6
  supabase_client: ^0.0.22
  telegram_client: ^0.5.66
  xendit: ^0.0.21
  zxing2: ^0.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
